controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: annotation
# config/routes.yaml
app_register:
    path: /inscription
    controller: App\Controller\RegistrationController::register
    methods: [GET, POST]
api_login_check:
    path: /api/login_check