<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOJNY14O\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOJNY14O/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOJNY14O.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOJNY14O\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOJNY14O\App_KernelDevDebugContainer([
    'container.build_hash' => 'OJNY14O',
    'container.build_id' => 'c6454143',
    'container.build_time' => 1679880920,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOJNY14O');
